# Generated by Django 2.2.1 on 2019-09-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
    ]
