# Generated by Django 2.2.3 on 2019-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_login_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='senha',
            field=models.CharField(default='', max_length=100, verbose_name='Senha'),
        ),
    ]
